sudo: required
language: generic

# use docker for builds
services:
  - docker

# docker docker test image for testing
before_install:
  - docker build -t pointguard2000/react-test -f ./client/Dockerfile.dev ./client

# run all tests using docker comand
script:
  - docker run -e CI=true pointguard2000/react-test npm test

after_success:
  # build all images
  - docker build -t pointguard2000/multi-client ./client
  - docker build -t pointguard2000/multi-nginx ./nginx
  - docker build -t pointguard2000/multi-server ./server
  - docker build -t pointguard2000/multi-worker ./worker

  # log into docker CLI
  - echo "$DOCKER_PASSWORD" docker login -u "$DOCKER_ID" --password-stdin

  # take images and push to docker hub
  - docker push pointguard2000/multi-client
  - docker push pointguard2000/multi-nginx
  - docker push pointguard2000/multi-server
  - docker push pointguard2000/multi-worker
